# Generated by Django 4.2.16 on 2026-04-17 20:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ScanResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('repo_owner', models.CharField(max_length=255)),
                ('repo_name', models.CharField(max_length=255)),
                ('repo_full_name', models.CharField(max_length=512)),
                ('scanner_type', models.CharField(default='bandit', max_length=50)),
                ('status', models.CharField(choices=[('PENDING', 'En attente'), ('RUNNING', 'En cours'), ('COMPLETED', 'Terminée'), ('FAILED', 'Échouée')], default='PENDING', max_length=20)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('raw_output', models.TextField(blank=True)),
                ('total_issues', models.IntegerField(default=0)),
                ('critical_count', models.IntegerField(default=0)),
                ('high_count', models.IntegerField(default=0)),
                ('medium_count', models.IntegerField(default=0)),
                ('low_count', models.IntegerField(default=0)),
                ('run_sast', models.BooleanField(default=True)),
                ('run_sca', models.BooleanField(default=False)),
                ('sca_status', models.CharField(choices=[('PENDING', 'En attente'), ('RUNNING', 'En cours'), ('COMPLETED', 'Terminée'), ('FAILED', 'Échouée')], default='PENDING', max_length=20)),
                ('sca_critical_count', models.IntegerField(default=0)),
                ('sca_high_count', models.IntegerField(default=0)),
                ('sca_medium_count', models.IntegerField(default=0)),
                ('sca_low_count', models.IntegerField(default=0)),
                ('run_dast', models.BooleanField(default=False)),
                ('dast_status', models.CharField(choices=[('PENDING', 'En attente'), ('RUNNING', 'En cours'), ('COMPLETED', 'Terminée'), ('FAILED', 'Échouée')], default='PENDING', max_length=20)),
                ('dast_target_url', models.URLField(blank=True, max_length=2048)),
                ('dast_critical_count', models.IntegerField(default=0)),
                ('dast_high_count', models.IntegerField(default=0)),
                ('dast_medium_count', models.IntegerField(default=0)),
                ('dast_low_count', models.IntegerField(default=0)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='scans', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Résultat de scan',
                'verbose_name_plural': 'Résultats de scan',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='Vulnerability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_id', models.CharField(max_length=50)),
                ('test_name', models.CharField(max_length=255)),
                ('issue_text', models.TextField()),
                ('severity', models.CharField(choices=[('CRITICAL', 'Critique'), ('HIGH', 'Haute'), ('MEDIUM', 'Moyenne'), ('LOW', 'Faible')], max_length=10)),
                ('confidence', models.CharField(choices=[('HIGH', 'Haute'), ('MEDIUM', 'Moyenne'), ('LOW', 'Basse')], max_length=10)),
                ('filename', models.CharField(max_length=500)),
                ('line_number', models.IntegerField()),
                ('line_range', models.JSONField(default=list)),
                ('code_snippet', models.TextField(blank=True)),
                ('cwe', models.CharField(blank=True, max_length=50)),
                ('llm_score', models.FloatField(default=0.0)),
                ('llm_explanation', models.TextField(blank=True)),
                ('is_sca', models.BooleanField(default=False)),
                ('is_dast', models.BooleanField(default=False)),
                ('solution', models.TextField(blank=True)),
                ('more_info', models.URLField(blank=True, max_length=1000)),
                ('scan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vulnerabilities', to='scans.scanresult')),
            ],
            options={
                'verbose_name': 'Vulnérabilité',
                'verbose_name_plural': 'Vulnérabilités',
                'ordering': ['-llm_score', '-severity', 'filename', 'line_number'],
            },
        ),
        migrations.CreateModel(
            name='ApiUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rag_calls_count', models.IntegerField(default=0)),
                ('rag_calls_limit', models.IntegerField(default=100)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='api_usage', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
