# Generated by Django 4.2.16 on 2026-04-21 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scans', '0002_add_rag_cache_to_vulnerability'),
    ]

    operations = [
        migrations.AddField(
            model_name='scanresult',
            name='container_critical_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='scanresult',
            name='container_high_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='scanresult',
            name='container_low_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='scanresult',
            name='container_medium_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='scanresult',
            name='container_status',
            field=models.CharField(choices=[('PENDING', 'En attente'), ('RUNNING', 'En cours'), ('COMPLETED', 'Terminée'), ('FAILED', 'Échouée')], default='PENDING', max_length=20),
        ),
        migrations.AddField(
            model_name='scanresult',
            name='run_container',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='vulnerability',
            name='is_container',
            field=models.BooleanField(default=False),
        ),
    ]
