# Generated by Django 4.2.16 on 2026-04-22 11:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('scans', '0003_scanresult_container_critical_count_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GitHubAppInstallation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('installation_id', models.BigIntegerField(unique=True)),
                ('github_account_login', models.CharField(max_length=255)),
                ('github_account_id', models.BigIntegerField()),
                ('github_account_type', models.CharField(max_length=50)),
                ('repositories', models.JSONField(blank=True, default=list)),
                ('status', models.CharField(default='active', max_length=20)),
                ('setup_completed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='github_app_installations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Installation GitHub App',
                'verbose_name_plural': 'Installations GitHub App',
            },
        ),
    ]
