# Generated by Django 4.2.16 on 2026-04-17 20:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GitHubProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('github_id', models.BigIntegerField(unique=True)),
                ('github_login', models.CharField(max_length=255)),
                ('github_name', models.CharField(blank=True, max_length=255)),
                ('github_email', models.CharField(blank=True, max_length=255)),
                ('github_avatar_url', models.URLField(blank=True)),
                ('github_access_token', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='github_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Profil GitHub',
                'verbose_name_plural': 'Profils GitHub',
            },
        ),
    ]
