version: '3'

services:
  postgres:
    image: postgres:14-alpine
    container_name: defectdojo-postgres
    environment:
      - POSTGRES_DB=defectdojo
      - POSTGRES_USER=defectdojo
      - POSTGRES_PASSWORD=defectdojo
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always

  redis:
    image: redis:6-alpine
    container_name: defectdojo-redis
    restart: always

  uwsgi:
    image: defectdojo/defectdojo-django:latest
    container_name: defectdojo-uwsgi
    environment:
      - DD_DATABASE_URL=postgresql://defectdojo:defectdojo@postgres:5432/defectdojo
      - DD_SECRET_KEY=pfe_secret_key_123
      - DD_URL_PREFIX=
      - DD_X_FRAME_OPTIONS=ALLOWALL
      - DD_CSRF_TRUSTED_ORIGINS=http://localhost:5173,http://localhost:8000,http://localhost:8080
      - DD_SECURE_SSL_REDIRECT=False
    depends_on:
      - postgres
      - redis
    volumes:
      - ./data:/app/data
    restart: always

  nginx:
    image: defectdojo/defectdojo-nginx:latest
    container_name: defectdojo-nginx
    ports:
      - "8080:8080"
    depends_on:
      - uwsgi
    environment:
      - DD_UWSGI_HOST=uwsgi
      - DD_UWSGI_PORT=3031
    restart: always

volumes:
  postgres_data:
